### Rahven's VENTURI

#### Jolpica Historical Dataset Preparation

This notebook prepares the official Jolpica Formula One historical dataset for downstream analysis.

Pipeline Overview:

1. Configure project paths
2. Locate the official Jolpica archive
3. Extract archive contents
4. Validate extracted files
5. Generate dataset metadata
6. Convert CSV files to Parquet (optional)
7. Save processed datasets
8. Generate preparation logs

This notebook is part of the Rahven's VENTURI Formula One Data Platform.

In [1]:
from pathlib import Path
from zipfile import ZipFile
import shutil
import hashlib
import json
from datetime import datetime

import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", 100)

In [3]:

# Project Root

PROJECT_ROOT = Path.cwd().parent

# Data Directories

DATA_DIR = PROJECT_ROOT / "data"

RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

# Jolpica Directories

JOLPICA_DIR = RAW_DIR / "jolpica"

ARCHIVE_DIR = JOLPICA_DIR / "archive"
EXTRACTED_DIR = JOLPICA_DIR / "extracted"
METADATA_DIR = JOLPICA_DIR / "metadata"

PROCESSED_JOLPICA_DIR = PROCESSED_DIR / "jolpica"

# Logs

LOG_DIR = PROJECT_ROOT / "logs"

In [4]:
required_directories = [
    ARCHIVE_DIR,
    EXTRACTED_DIR,
    METADATA_DIR,
    PROCESSED_JOLPICA_DIR,
    LOG_DIR,
]

for directory in required_directories:
    directory.mkdir(parents=True, exist_ok=True)

print("Directory structure verified.")

Directory structure verified.

In [5]:
print("Rahven's VENTURI")
print("-" * 50)

print(f"Project Root : {PROJECT_ROOT}")
print(f"Archive      : {ARCHIVE_DIR}")
print(f"Extracted    : {EXTRACTED_DIR}")
print(f"Processed    : {PROCESSED_JOLPICA_DIR}")
print(f"Metadata     : {METADATA_DIR}")
print(f"Logs         : {LOG_DIR}")

Rahven's VENTURI
--------------------------------------------------
Project Root : C:\F1-AI
Archive      : C:\F1-AI\data\raw\jolpica\archive
Extracted    : C:\F1-AI\data\raw\jolpica\extracted
Processed    : C:\F1-AI\data\processed\jolpica
Metadata     : C:\F1-AI\data\raw\jolpica\metadata
Logs         : C:\F1-AI\logs

In [6]:
# Locate Jolpica Archive

zip_files = sorted(ARCHIVE_DIR.glob("*.zip"))

if not zip_files:
    raise FileNotFoundError(
        f"No ZIP archive found in:\n{ARCHIVE_DIR}"
    )

if len(zip_files) > 1:
    print("Multiple archives detected:")
    for file in zip_files:
        print(f"  • {file.name}")

JOLPICA_ZIP = max(
    zip_files,
    key=lambda file: file.stat().st_mtime
)

print(f"Using archive:\n{JOLPICA_ZIP.name}")

Using archive:
jolpica_db_csv.zip

In [7]:
archive_size = JOLPICA_ZIP.stat().st_size / (1024 * 1024)

print("Archive Information")
print("-" * 50)

print(f"Filename : {JOLPICA_ZIP.name}")
print(f"Size     : {archive_size:.2f} MB")
print(f"Modified : {datetime.fromtimestamp(JOLPICA_ZIP.stat().st_mtime)}")

Archive Information
--------------------------------------------------
Filename : jolpica_db_csv.zip
Size     : 13.53 MB
Modified : 2026-07-21 00:23:48.604541

In [8]:
def calculate_sha256(file_path: Path) -> str:
    sha256 = hashlib.sha256()

    with file_path.open("rb") as file:

        while True:
            chunk = file.read(1024 * 1024)

            if not chunk:
                break

            sha256.update(chunk)

    return sha256.hexdigest()


archive_sha256 = calculate_sha256(JOLPICA_ZIP)

print("SHA256")
print("-" * 50)
print(archive_sha256)

SHA256
--------------------------------------------------
672a4b7deb394777506ebe928452df1d5c426354cb51e0ffd0774881fd7e8e6f

In [9]:
with ZipFile(JOLPICA_ZIP, "r") as archive:

    archive_members = archive.namelist()

print(f"Total files inside archive : {len(archive_members)}")

pd.DataFrame({
    "Archive Contents": archive_members
})

Total files inside archive : 18

                          Archive Contents
0                 formula_one_baseteam.csv
1   formula_one_championshipadjustment.csv
2       formula_one_championshipsystem.csv
3                  formula_one_circuit.csv
4                   formula_one_driver.csv
5       formula_one_driverchampionship.csv
6                      formula_one_lap.csv
7                  formula_one_penalty.csv
8                  formula_one_pitstop.csv
9              formula_one_pointsystem.csv
10                   formula_one_round.csv
11              formula_one_roundentry.csv
12                  formula_one_season.csv
13                 formula_one_session.csv
14            formula_one_sessionentry.csv
15                    formula_one_team.csv
16        formula_one_teamchampionship.csv
17              formula_one_teamdriver.csv

In [10]:
# Remove Previous Extraction

if EXTRACTED_DIR.exists():

    shutil.rmtree(EXTRACTED_DIR)

EXTRACTED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Extraction directory cleaned.")

Extraction directory cleaned.

In [11]:
with ZipFile(JOLPICA_ZIP, "r") as archive:

    archive.extractall(EXTRACTED_DIR)

print("Archive extracted successfully.")

Archive extracted successfully.

In [12]:
csv_files = sorted(EXTRACTED_DIR.glob("*.csv"))

print(f"CSV files discovered : {len(csv_files)}")

csv_inventory = pd.DataFrame({

    "Table": [file.stem for file in csv_files],
    "Filename": [file.name for file in csv_files]

})

csv_inventory

CSV files discovered : 18

                                 Table                                Filename
0                 formula_one_baseteam                formula_one_baseteam.csv
1   formula_one_championshipadjustment  formula_one_championshipadjustment.csv
2       formula_one_championshipsystem      formula_one_championshipsystem.csv
3                  formula_one_circuit                 formula_one_circuit.csv
4                   formula_one_driver                  formula_one_driver.csv
5       formula_one_driverchampionship      formula_one_driverchampionship.csv
6                      formula_one_lap                     formula_one_lap.csv
7                  formula_one_penalty                 formula_one_penalty.csv
8                  formula_one_pitstop                 formula_one_pitstop.csv
9              formula_one_pointsystem             formula_one_pointsystem.csv
10                   formula_one_round                   formula_one_round.csv
11              formula_one_roundentry              formula_one_roundentry.csv
12                  formula_one_season                  formula_one_season.csv
13                 formula_one_session                 formula_one_session.csv
14            formula_one_sessionentry            formula_one_sessionentry.csv
15                    formula_one_team                    formula_one_team.csv
16        formula_one_teamchampionship        formula_one_teamchampionship.csv
17              formula_one_teamdriver              formula_one_teamdriver.csv

In [13]:
expected_tables = {
    "formula_one_baseteam",
    "formula_one_championshipadjustment",
    "formula_one_championshipsystem",
    "formula_one_circuit",
    "formula_one_driver",
    "formula_one_driverchampionship",
    "formula_one_lap",
    "formula_one_penalty",
    "formula_one_pitstop",
    "formula_one_pointsystem",
    "formula_one_round",
    "formula_one_roundentry",
    "formula_one_season",
    "formula_one_session",
    "formula_one_sessionentry",
    "formula_one_team",
    "formula_one_teamchampionship",
    "formula_one_teamdriver",
}

found_tables = {
    file.stem
    for file in csv_files
}

missing_tables = expected_tables - found_tables
extra_tables = found_tables - expected_tables

print(f"Expected : {len(expected_tables)}")
print(f"Found    : {len(found_tables)}")

if missing_tables:
    print("\nMissing Tables")
    print("----------------")

    for table in sorted(missing_tables):
        print(table)

if extra_tables:
    print("\nUnexpected Tables")
    print("-------------------")

    for table in sorted(extra_tables):
        print(table)

if not missing_tables and not extra_tables:
    print("\nDataset validation passed.")

Expected : 18
Found    : 18

Dataset validation passed.

In [14]:
# Load All CSV Tables

tables = {}

for csv_file in sorted(EXTRACTED_DIR.glob("*.csv")):

    table_name = csv_file.stem

    tables[table_name] = pd.read_csv(csv_file)

print(f"Successfully loaded {len(tables)} tables.")

Successfully loaded 18 tables.

In [15]:
dataset_summary = []

for table_name, df in tables.items():

    dataset_summary.append({

        "Table": table_name,
        "Rows": len(df),
        "Columns": df.shape[1],
        "Memory (MB)": round(df.memory_usage(deep=True).sum() / (1024 ** 2), 2)

    })

summary_df = (
    pd.DataFrame(dataset_summary)
      .sort_values("Table")
      .reset_index(drop=True)
)

summary_df

                                 Table    Rows  Columns  Memory (MB)
0                 formula_one_baseteam       0        3         0.00
1   formula_one_championshipadjustment       3        7         0.00
2       formula_one_championshipsystem      11       10         0.00
3                  formula_one_circuit      78       11         0.04
4                   formula_one_driver     881       11         0.45
5       formula_one_driverchampionship   36003       14         5.29
6                      formula_one_lap  715463        9       178.69
7                  formula_one_penalty       0        8         0.00
8                  formula_one_pitstop   12672        7         2.60
9              formula_one_pointsystem      24       11         0.01
10                   formula_one_round    1173       10         0.43
11              formula_one_roundentry   27499        5         2.62
12                  formula_one_season      77        5         0.01
13                 formula_one_session    5130       11         1.92
14            formula_one_sessionentry   50706       14        15.42
15                    formula_one_team     214        9         0.09
16        formula_one_teamchampionship   14161       14         2.08
17              formula_one_teamdriver    3627        6         0.37

---------------------------
### **Total Dataset Statistics**

In [16]:
total_rows = sum(df.shape[0] for df in tables.values())
total_columns = sum(df.shape[1] for df in tables.values())
total_memory = sum(
    df.memory_usage(deep=True).sum()
    for df in tables.values()
) / (1024 ** 2)

print("Jolpica Dataset Summary")
print("-" * 50)

print(f"Tables          : {len(tables)}")
print(f"Total Rows      : {total_rows:,}")
print(f"Total Columns   : {total_columns}")
print(f"Memory Usage    : {total_memory:.2f} MB")

Jolpica Dataset Summary
--------------------------------------------------
Tables          : 18
Total Rows      : 867,722
Total Columns   : 165
Memory Usage    : 210.03 MB

-------------------------------
### **Peeking at each table**

In [17]:
for table_name, df in tables.items():

    print("=" * 80)
    print(table_name)
    print("=" * 80)

    display(df.head(3))

================================================================================
formula_one_baseteam
================================================================================

Empty DataFrame
Columns: [id, api_id, name]
Index: []

================================================================================
formula_one_championshipadjustment
================================================================================

   id  adjustment                           api_id  driver_id  points  season_id  team_id
0   1         101  championshipadjustment_ytJcOgGB      703.0     NaN         48      NaN
1   2         102  championshipadjustment_yy7ogVVY        NaN     NaN         58    117.0
2   3           1  championshipadjustment_zXL6omRH        NaN    15.0         71    208.0

================================================================================
formula_one_championshipsystem
================================================================================

,id,api_id,driver_best_results,driver_season_split,eligibility,name,reference,team_best_results,team_points_per_session,team_season_split
0,1,championshipsystem_nOtKOEQW,4,0,1,1950 - 1953 Championship,s1950,0,0,0
1,2,championshipsystem_34z7l8W7,5,0,1,1954 - 1957 Championship,s1954,0,0,0
2,3,championshipsystem_EEmoioVr,6,0,1,"1958, 1960, 1963-1965\tChampionship",s1958,6,1,0

================================================================================
formula_one_circuit
================================================================================

,id,altitude,api_id,country,country_code,latitude,locality,longitude,name,reference,wikipedia
0,1,153,circuit_W8rwFAJs,UK,GBR,52.0786,Silverstone,-1.01694,Silverstone Circuit,silverstone,https://en.wikipedia.org/wiki/Silverstone_Circuit
1,2,7,circuit_r30Ojrot,Monaco,MCO,43.7347,Monte Carlo,7.42056,Circuit de Monaco,monaco,https://en.wikipedia.org/wiki/Circuit_de_Monaco
2,3,223,circuit_fcUWpmRF,USA,USA,39.7950,Indianapolis,-86.23470,Indianapolis Motor Speedway,indianapolis,https://en.wikipedia.org/wiki/Indianapolis_Motor_Speedway

================================================================================
formula_one_driver
================================================================================

,id,abbreviation,api_id,country_code,date_of_birth,forename,nationality,permanent_car_number,reference,surname,wikipedia
0,1,NaN,driver_NNme7ruE,ITA,1906-10-30,Nino,Italian,NaN,farina,Farina,http://en.wikipedia.org/wiki/Nino_Farina
1,2,NaN,driver_oSJ2AZ19,ITA,1898-06-09,Luigi,Italian,NaN,fagioli,Fagioli,http://en.wikipedia.org/wiki/Luigi_Fagioli
2,3,NaN,driver_K1dAqP21,GBR,1911-07-02,Reg,British,NaN,reg_parnell,Parnell,http://en.wikipedia.org/wiki/Reg_Parnell

================================================================================
formula_one_driverchampionship
================================================================================

,id,adjustment_type,driver_id,highest_finish,is_eligible,points,position,round_id,round_number,season_id,session_id,session_number,win_count,year
0,425647,0,847,NaN,t,0.0,1.0,NaN,1,NaN,5134,4,0,2026
1,425648,0,857,NaN,t,0.0,2.0,NaN,1,NaN,5134,4,0,2026
2,425649,0,795,NaN,t,0.0,3.0,NaN,1,NaN,5134,4,0,2026

================================================================================
formula_one_lap
================================================================================

   id        api_id  average_speed is_deleted is_entry_fastest_lap  number  position  session_entry_id          time
0   1  lap_xFAdrriK            NaN          f                    t     NaN       NaN             14403   00:01:16.29
1   2  lap_OEwGuAbN            NaN          f                    t     NaN       NaN             14405  00:01:17.554
2   3  lap_iLkEWF5w            NaN          f                    t     NaN       NaN             14407  00:01:17.385

================================================================================
formula_one_penalty
================================================================================

Empty DataFrame
Columns: [id, api_id, earned_id, is_time_served_in_pit, license_points, position, served_id, time]
Index: []

================================================================================
formula_one_pitstop
================================================================================

   id            api_id      duration  lap_id local_timestamp  number  session_entry_id
0   1  pitstop_IYavKg2C  00:00:24.036  275638        17:59:17       2             27696
1   2  pitstop_XDzyA9tn  00:00:22.603  275672        17:25:17       1             27696
2   3  pitstop_c0OV7PJY  00:00:23.227  275742        17:28:24       1             27700

================================================================================
formula_one_pointsystem
================================================================================

,id,api_id,driver_fastest_lap,driver_position_points,is_double_points,name,partial,reference,shared_drive,team_fastest_lap,team_position_points
0,1,pointsystem_te7U11qP,0,0,f,Session with no Points Awarded,0,No Points,0,0,0
1,2,pointsystem_aedyNBvz,1,1,f,1950-1953 Race Points,0,r1950,1,0,0
2,3,pointsystem_36p48Ou0,2,1,f,1954 Race Points,0,r1954,1,0,0

================================================================================
formula_one_round
================================================================================

,id,api_id,circuit_id,date,is_cancelled,name,number,race_number,season_id,wikipedia
0,1,round_Pt9PwCgv,1,1950-05-13,f,British Grand Prix,1.0,1.0,1,https://en.wikipedia.org/wiki/1950_British_Grand_Prix
1,2,round_cAbLcO1L,2,1950-05-21,f,Monaco Grand Prix,2.0,2.0,1,https://en.wikipedia.org/wiki/1950_Monaco_Grand_Prix
2,3,round_RhrrZnkp,3,1950-05-30,f,Indianapolis 500,3.0,3.0,1,https://en.wikipedia.org/wiki/1950_Indianapolis_500

================================================================================
formula_one_roundentry
================================================================================

   id               api_id  car_number  round_id  team_driver_id
0   1  roundentry_FUFWqiHA         2.0         1               1
1   2  roundentry_X2Oso05J         3.0         1               2
2   3  roundentry_wjjINPdb         4.0         1               3

================================================================================
formula_one_season
================================================================================

   id           api_id  championship_system_id                                              wikipedia  year
0   1  season_oPqQEC4b                       1  https://en.wikipedia.org/wiki/1950_Formula_One_season  1950
1   2  season_nH07GTj5                       1  https://en.wikipedia.org/wiki/1951_Formula_One_season  1951
2   3  season_AkHDeRX4                       1  https://en.wikipedia.org/wiki/1952_Formula_One_season  1952

================================================================================
formula_one_session
================================================================================

,id,api_id,has_time_data,is_cancelled,number,point_system_id,round_id,scheduled_laps,timestamp,timezone,type
0,1,session_8sj3ZIRr,f,f,3.0,2,1,NaN,1950-05-13 00:00:00+00:00,Europe/London,R
1,2,session_wekmWw64,f,f,1.0,1,1,NaN,1950-05-11 00:00:00+00:00,Europe/London,QB
2,3,session_OqpKUX18,f,f,2.0,1,1,NaN,1950-05-12 00:00:00+00:00,Europe/London,QB

================================================================================
formula_one_sessionentry
================================================================================

,id,api_id,detail,fastest_lap_rank,grid,is_classified,is_eligible_for_points,laps_completed,points,position,round_entry_id,session_id,status,time
0,1,sessionentry_AJVCqvHP,Finished,NaN,1.0,t,t,70.0,9.0,1.0,1,1,0.0,02:13:23.6
1,2,sessionentry_nTuoeGU3,Finished,NaN,2.0,t,t,70.0,6.0,2.0,2,1,0.0,02:13:26.2
2,3,sessionentry_YtaG16NK,Finished,NaN,4.0,t,t,70.0,4.0,3.0,3,1,0.0,02:14:15.6

================================================================================
formula_one_team
================================================================================

,id,api_id,base_team_id,country_code,name,nationality,primary_color,reference,wikipedia
0,1,team_1XDKqgNu,NaN,CHE,Alfa Romeo,Swiss,NaN,alfa,https://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One
1,2,team_e9i5UU0k,NaN,ITA,Maserati,Italian,NaN,maserati,https://en.wikipedia.org/wiki/Maserati
2,3,team_R6ZNEH9U,NaN,GBR,Alta,British,NaN,alta,https://en.wikipedia.org/wiki/Alta_Car_and_Engineering_Company

================================================================================
formula_one_teamchampionship
================================================================================

,id,adjustment_type,highest_finish,is_eligible,points,position,round_id,round_number,season_id,session_id,session_number,team_id,win_count,year
0,197289,0,NaN,t,0.0,1.0,NaN,1,NaN,5134,4,191,0,2026
1,197290,0,NaN,t,0.0,2.0,NaN,1,NaN,5134,4,141,0,2026
2,197291,0,NaN,t,0.0,3.0,NaN,1,NaN,5134,4,64,0,2026

================================================================================
formula_one_teamdriver
================================================================================

   id               api_id  driver_id  role  season_id  team_id
0   1  teamdriver_LSox06Od          1   NaN          1        1
1   2  teamdriver_bLowFOCJ          2   NaN          1        1
2   3  teamdriver_d8PF1G74          3   NaN          1        1

----------------------------
### **Validate every table**

In [18]:
validation_summary = []

for table_name, df in tables.items():

    duplicate_rows = int(df.duplicated().sum())

    null_cells = int(df.isna().sum().sum())

    has_id = "id" in df.columns

    duplicate_ids = (
        int(df["id"].duplicated().sum())
        if has_id
        else None
    )

    null_ids = (
        int(df["id"].isna().sum())
        if has_id
        else None
    )

    validation_summary.append({
        "Table": table_name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Null Cells": null_cells,
        "Duplicate Rows": duplicate_rows,
        "Duplicate IDs": duplicate_ids,
        "Null IDs": null_ids,
        "Memory (MB)": round(
            df.memory_usage(deep=True).sum() / (1024 ** 2),
            2
        ),
    })

validation_df = (
    pd.DataFrame(validation_summary)
      .sort_values("Table")
      .reset_index(drop=True)
)

validation_df

,Table,Rows,Columns,Null Cells,Duplicate Rows,Duplicate IDs,Null IDs,Memory (MB)
0,formula_one_baseteam,0,3,0,0,0,0,0.00
1,formula_one_championshipadjustment,3,7,5,0,0,0,0.00
2,formula_one_championshipsystem,11,10,0,0,0,0,0.00
3,formula_one_circuit,78,11,0,0,0,0,0.04
4,formula_one_driver,881,11,1640,0,0,0,0.46
5,formula_one_driverchampionship,36003,14,53769,0,0,0,5.29
6,formula_one_lap,715463,9,809682,0,0,0,178.69
7,formula_one_penalty,0,8,0,0,0,0,0.00
8,formula_one_pitstop,12672,7,0,0,0,0,2.60
9,formula_one_pointsystem,24,11,0,0,0,0,0.01
10,formula_one_round,1173,10,4,0,0,0,0.43
11,formula_one_roundentry,27499,5,6,0,0,0,2.62
12,formula_one_season,77,5,0,0,0,0,0.01
13,formula_one_session,5130,11,5120,0,0,0,1.92
14,formula_one_sessionentry,50706,14,213093,0,0,0,15.42
15,formula_one_team,214,9,416,0,0,0,0.09
16,formula_one_teamchampionship,14161,14,18012,0,0,0,2.08
17,formula_one_teamdriver,3627,6,3556,0,0,0,0.37

**Convert csv --> Parquet**

In [19]:
for table_name, df in tables.items():

    output_path = PROCESSED_JOLPICA_DIR / f"{table_name}.parquet"

    df.to_parquet(
        output_path,
        index=False
    )

print(f"Converted {len(tables)} tables to Parquet.")

Converted 18 tables to Parquet.

In [20]:
metadata = {
    "created_at": datetime.now().isoformat(),
    "archive_name": JOLPICA_ZIP.name,
    "archive_sha256": archive_sha256,
    "table_count": len(tables),
    "total_rows": total_rows,
    "total_columns": total_columns,
    "total_memory_mb": round(total_memory, 2),
}

metadata_path = METADATA_DIR / "dataset_metadata.json"

with metadata_path.open("w", encoding="utf-8") as file:
    json.dump(metadata, file, indent=4)

print(f"Metadata saved:\n{metadata_path}")

Metadata saved:
C:\F1-AI\data\raw\jolpica\metadata\dataset_metadata.json

### **Final Pipeline Summary**

In [22]:
print("=" * 60)
print("Rahven's VENTURI - Jolpica Preparation Complete")
print("=" * 60)

print(f"Archive           : {JOLPICA_ZIP.name}")
print(f"Tables Loaded     : {len(tables)}")
print(f"Total Rows        : {total_rows:,}")
print(f"Processed Tables  : {len(tables)} Parquet files")
print(f"Metadata Folder   : {METADATA_DIR}")
print(f"Processed Folder  : {PROCESSED_JOLPICA_DIR}")

print("\nNext Notebook:")
print("04_jolpica_eda.ipynb")

============================================================
Rahven's VENTURI - Jolpica Preparation Complete
============================================================
Archive           : jolpica_db_csv.zip
Tables Loaded     : 18
Total Rows        : 867,722
Processed Tables  : 18 Parquet files
Metadata Folder   : C:\F1-AI\data\raw\jolpica\metadata
Processed Folder  : C:\F1-AI\data\processed\jolpica

Next Notebook:
04_jolpica_eda.ipynb

In [28]:
# -----------------------------
# Generate Schema Report
# -----------------------------

schema_rows = []

for table_name, df in tables.items():

    for column in df.columns:

        schema_rows.append({
            "Table": table_name,
            "Column": column,
            "Data Type": str(df[column].dtype),
            "Non-Null Count": int(df[column].count()),
            "Null Count": int(df[column].isna().sum()),
            "Unique Values": int(df[column].nunique(dropna=True))
        })

schema_df = (
    pd.DataFrame(schema_rows)
      .sort_values(["Table", "Column"])
      .reset_index(drop=True)
)

schema_path = METADATA_DIR / "schema_report.csv"

schema_df.to_csv(schema_path, index=False)

print(f"Schema report saved to:\n{schema_path}")

print(schema_df.head(20))
print(schema_df.shape)

Schema report saved to:
C:\F1-AI\data\raw\jolpica\metadata\schema_report.csv
                                 Table                   Column Data Type  Non-Null Count  Null Count  Unique Values
0                 formula_one_baseteam                   api_id    object               0           0              0
1                 formula_one_baseteam                       id    object               0           0              0
2                 formula_one_baseteam                     name    object               0           0              0
3   formula_one_championshipadjustment               adjustment     int64               3           0              3
4   formula_one_championshipadjustment                   api_id    object               3           0              3
5   formula_one_championshipadjustment                driver_id   float64               1           2              1
6   formula_one_championshipadjustment                       id     int64               3           0              3
7   formula_one_championshipadjustment                   points   float64               1           2              1
8   formula_one_championshipadjustment                season_id     int64               3           0              3
9   formula_one_championshipadjustment                  team_id   float64               2           1              2
10      formula_one_championshipsystem                   api_id    object              11           0             11
11      formula_one_championshipsystem      driver_best_results     int64              11           0              6
12      formula_one_championshipsystem      driver_season_split     int64              11           0              3
13      formula_one_championshipsystem              eligibility     int64              11           0              3
14      formula_one_championshipsystem                       id     int64              11           0             11
15      formula_one_championshipsystem                     name    object              11           0             11
16      formula_one_championshipsystem                reference    object              11           0             11
17      formula_one_championshipsystem        team_best_results     int64              11           0              5
18      formula_one_championshipsystem  team_points_per_session     int64              11           0              2
19      formula_one_championshipsystem        team_season_split     int64              11           0              2
(165, 6)